
name: build and test feature branch

# This workflow is triggered by a push to the repository.
on:
  push:
    branches:
      - feature/* #en toda rama que comience con la palabra feature

# A job to build the application with Maven and run unit tests.
jobs:
  build-feature: #nombre del job
    runs-on: ubuntu-latest #runner con la ultima version de ubuntu
    steps: #pasos

      # Descarga las fuentes
      - name: descarga las fuentes
        uses: actions/checkout@v4 #action para descargar las fuentes obtenido desde https://github.com/marketplace?type=actions tod action inicia con el nombre uses
      
      #Muestra un mensaje
         run: |
         echo "descargando las fuentes"

      # Configura Java
      - name: Ejecuta una fuente java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      # Ejecuta Maven
      - name: Ejecuta Maven
        run: |
          mvnw clean install
          echo "Ejecutado con Maven"
